services:
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_PATH=/app/tasks.db
      - HTTP_ADDRESS=0.0.0.0:8080
      - NOTIFICATION_SERVICE_ADDRESS=notifications:2000
    volumes:
      - ./tasks.db:/app/tasks.db
    depends_on:
      - notifications
    networks:
      - app-network

  notifications:
    build:
      context: .
      dockerfile: notifications/Dockerfile
    ports:
      - "2000:2000"
    environment:
      - DB_PATH=/app/tasks.db
      - NOTIFICATION_SERVICE_ADDRESS=0.0.0.0:2000
    volumes:
      - ./tasks.db:/app/tasks.db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
